[package]
name = "starchart"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "4.0"
thiserror = "1.0.30"

[dependencies.futures]
default-features = false
features = ["executor"]
version = "0.3"

[dependencies.futures-util]
default-features = false
features = ["std"]
version = "0.3"

[dependencies.serde]
default-features = false
features = ["derive"]
version = "1"

[dependencies.serde_json]
version = "1"
optional = true

[dependencies.serde-value]
version = "0.7"
optional = true

[dependencies.tokio]
default-features = false
features = ["fs"]
version = "1"
optional = true

[dependencies.tokio-stream]
default-features = false
features = ["fs"]
version = "0.1"
optional = true

[features]
default = ["json"]
json = ["serde_json", "serial"]
cache = ["serde-value"]
serial = ["tokio", "tokio-stream"]

[workspace]
members = ["./testing"]