[package]
authors = ["Gryffon Bellish <owenbellish@gmail.com>"]
description = "A database tool that allows for multiple backend implementations"
documentation = "https://docs.rs/starchart"
edition = "2018"
homepage = "https://github.com/starlite-project/starchart"
license = "MIT"
name = "starchart"
readme = "README.md"
repository = "https://github.com/starlite-project/starchart"
version = "0.3.0"

[dependencies]
dashmap = "4.0"
thiserror = "1.0.30"

[dependencies.futures]
default-features = false
features = ["executor"]
version = "0.3"

[dependencies.futures-util]
default-features = false
features = ["std"]
version = "0.3"

[dependencies.parking_lot]
git = "https://github.com/Amanieu/parking_lot"
rev = "f9e567392c43461dad4211954902f476da46e993"

[dependencies.serde]
default-features = false
features = ["derive"]
version = "1"

[dependencies.serde_json]
optional = true
version = "1"

[dependencies.serde-value]
optional = true
version = "0.7"

[dependencies.starchart-derive]
optional = true
path = "./starchart-derive"
version = "^0.3"

[dependencies.tokio]
default-features = false
features = ["fs"]
optional = true
version = "1"

[dependencies.tokio-stream]
default-features = false
features = ["fs"]
optional = true
version = "0.1"

[dev-dependencies]
static_assertions = "1.0.0"

[dev-dependencies.futures]
default-features = false
features = ["executor"]
version = "0.3"

[features]
cache = ["serde-value"]
default = ["json"]
derive = ["starchart-derive"]
fs = ["tokio", "tokio-stream"]
unstable-atomics = []
json = ["serde_json", "fs"]

[workspace]
members = [
  "./starchart-derive",
]

[package.metadata.docs.rs]
all-features = true
