name: Check documentation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
      
      - name: Build docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --workspace --no-deps --all-features

      - name: Upload docs
        uses: actions/upload-artifact@v2
        with:
          name: docs-artifact
          path: ./target/doc
  deploy-docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    needs: build-docs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Prepare docs
        run: |
          echo '<meta http-equiv="refresh" content="0;url=starchart/index.html">' > target/doc/index.html
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/doc
          allow_empty_commit: true