name: "Pull request labeler"
on:
  pull_request_target:
    types: [opened, synchronize, edited, reopened]

jobs:
  labeler:
    name: Label pull request
    runs-on: ubuntu-latest

    steps:
      - uses: fuxingloh/multi-labeler@v1
