name: Testing actions

on: [push, pull_request]

jobs:
  foo:
    name: foo
    runs-on: ubuntu-latest

    steps:
      - run: echo "foo 1"
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build-docs

    steps:
      - run: echo "foo"