name: Test

on: 
  push:
  pull_request:
    types: [opened, reopened]
    

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1

      - name: Remove old matchers
        run: echo "::remove-matcher owner=rust::"

      - name: Add problem matchers
        run: echo "::add-matcher::.github/problemMatchers/rust.json"
      
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: test

    container:
        image: xd009642/tarpaulin:develop-nightly
        options: --security-opt seccomp=unconfined

    steps: 
      - name: Checkout sources
        uses: actions/checkout@v2
      
      - name: Collect coverage
        uses: actions-rs/cargo@v1
        with:
          command: tarpaulin

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
      
      - name: Archive code coverage
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: cobertura.xml